// 大考中心高中英文參考詞彙表 Level 1–6
// 格式：[單字, 詞性, 中文意思, 等級, 英文例句, 中文例句翻譯]
const VOCAB = [
  // ── Level 1 ──────────────────────────────────────────────────────────────
  ["able","adj.","能夠的",1,"Are you able to help me?","你能幫我嗎？"],
  ["act","n./v.","行動/表演",1,"We must act quickly.","我們必須迅速行動。"],
  ["add","v.","增加",1,"Add some salt to the soup.","在湯裡加一些鹽。"],
  ["adult","n./adj.","成人",1,"This movie is for adults only.","這部電影僅限成人觀看。"],
  ["after","prep./conj.","在...之後",1,"Let's meet after school.","放學後見面吧。"],
  ["again","adv.","再一次",1,"Please say that again.","請再說一遍。"],
  ["age","n./v.","年齡",1,"What is your age?","你幾歲？"],
  ["agree","v.","同意",1,"I agree with your point.","我同意你的觀點。"],
  ["air","n.","空氣",1,"The air is fresh in the morning.","早上的空氣很清新。"],
  ["all","adj./adv.","全部",1,"All students must attend.","所有學生都必須出席。"],
  ["allow","v.","允許",1,"Dogs are not allowed inside.","裡面不允許帶狗進入。"],
  ["also","adv.","也",1,"She also likes reading.","她也喜歡閱讀。"],
  ["always","adv.","總是",1,"He always arrives on time.","他總是準時到達。"],
  ["anger","n.","憤怒",1,"Take a deep breath to control your anger.","深呼吸來控制你的憤怒。"],
  ["angry","adj.","憤怒的",1,"She was angry at the news.","她對這個消息感到憤怒。"],
  ["animal","n.","動物",1,"A dog is a loyal animal.","狗是忠誠的動物。"],
  ["answer","n./v.","回答",1,"Please answer the question.","請回答這個問題。"],
  ["apple","n.","蘋果",1,"An apple a day keeps the doctor away.","一天一蘋果，醫生遠離我。"],
  ["around","prep./adv.","在...周圍",1,"The children ran around the park.","孩子們在公園裡跑來跑去。"],
  ["art","n.","藝術",1,"She has a talent for art.","她有藝術才能。"],
  ["ask","v.","詢問",1,"Please ask if you have questions.","如果有問題請提問。"],
  ["away","adv.","離開",1,"He ran away from the dog.","他跑開逃離那隻狗。"],
  ["baby","n.","嬰兒",1,"The baby smiled at her mother.","嬰兒對她的媽媽微笑。"],
  ["back","n./adv.","背/後面",1,"Please step back.","請向後退一步。"],
  ["bad","adj.","不好的",1,"Smoking is a bad habit.","吸菸是個壞習慣。"],
  ["ball","n.","球",1,"Kick the ball into the goal.","把球踢進球門。"],
  ["bank","n.","銀行/河岸",1,"I go to the bank every Friday.","我每週五去銀行。"],
  ["beautiful","adj.","美麗的",1,"What a beautiful sunset!","多美麗的日落啊！"],
  ["because","conj.","因為",1,"She stayed home because it was raining.","她待在家裡因為下雨了。"],
  ["bed","n.","床",1,"Go to bed early tonight.","今晚早點上床睡覺。"],
  ["big","adj.","大的",1,"This is a big city.","這是一座大城市。"],
  ["bird","n.","鳥",1,"The bird sang a sweet song.","那隻鳥唱了一首悅耳的歌。"],
  ["black","adj./n.","黑色的",1,"She wore a black dress.","她穿了一件黑色洋裝。"],
  ["blue","adj./n.","藍色的",1,"The sky is blue today.","今天天空是藍色的。"],
  ["book","n./v.","書/預訂",1,"I love reading books.","我喜歡讀書。"],
  ["boy","n.","男孩",1,"The boy played in the garden.","那個男孩在花園裡玩耍。"],
  ["break","v./n.","打破/休息",1,"Don't break the glass.","不要打破玻璃。"],
  ["bring","v.","帶來",1,"Please bring your ID.","請帶你的身分證。"],
  ["brother","n.","兄弟",1,"My brother is two years older than me.","我哥哥比我大兩歲。"],
  ["bus","n.","公車",1,"Take the bus to school.","搭公車去學校。"],
  ["buy","v.","購買",1,"I want to buy a new phone.","我想買一支新手機。"],
  ["call","v./n.","打電話/叫",1,"Call me when you arrive.","到了打電話給我。"],
  ["car","n.","汽車",1,"My dad drives a red car.","我爸爸開一輛紅色汽車。"],
  ["care","n./v.","關心",1,"Care for others as you care for yourself.","關心他人就像關心自己一樣。"],
  ["cat","n.","貓",1,"My cat sleeps all day.","我的貓整天睡覺。"],
  ["change","n./v.","改變",1,"Change is part of life.","改變是生活的一部分。"],
  ["child","n.","孩子",1,"Every child deserves love.","每個孩子都值得被愛。"],
  ["choose","v.","選擇",1,"Choose the right path for yourself.","為自己選擇正確的道路。"],
  ["city","n.","城市",1,"Taipei is a busy city.","台北是一個繁忙的城市。"],
  ["class","n.","班級/課",1,"Our class starts at eight.","我們的課八點開始。"],
  ["clean","adj./v.","乾淨的/清潔",1,"Keep your room clean.","保持你的房間整潔。"],
  ["cold","adj./n.","冷的/感冒",1,"It is very cold in winter.","冬天非常冷。"],
  ["color","n.","顏色",1,"What is your favorite color?","你最喜歡的顏色是什麼？"],
  ["come","v.","來",1,"Come here, please.","請過來這裡。"],
  ["cook","v./n.","烹飪/廚師",1,"My mom cooks dinner every day.","我媽媽每天做晚飯。"],
  ["cut","v.","切割",1,"Please cut the paper in half.","請把紙對半剪開。"],
  ["day","n.","天/白天",1,"Have a nice day!","祝你有美好的一天！"],
  ["do","v.","做",1,"Do your best!","盡你所能！"],
  ["dog","n.","狗",1,"The dog wagged its tail.","那隻狗搖著尾巴。"],
  ["door","n.","門",1,"Please close the door.","請關門。"],
  ["dream","n./v.","夢想",1,"Never stop chasing your dream.","永遠不要停止追逐你的夢想。"],
  ["drink","v./n.","喝/飲料",1,"Drink plenty of water each day.","每天多喝水。"],
  ["drive","v.","駕駛",1,"She learned to drive at eighteen.","她在十八歲學會開車。"],
  ["eat","v.","吃",1,"Eat your vegetables!","把你的蔬菜吃掉！"],
  ["enjoy","v.","享受",1,"I enjoy reading before bed.","我喜歡睡前閱讀。"],
  ["eye","n.","眼睛",1,"She has beautiful brown eyes.","她有一雙美麗的棕色眼睛。"],
  ["face","n./v.","臉/面對",1,"Wash your face before breakfast.","早餐前洗臉。"],
  ["family","n.","家庭",1,"Family is the most important thing.","家庭是最重要的事。"],
  ["fast","adj./adv.","快的/快速地",1,"Run as fast as you can.","盡你所能地跑快。"],
  ["feel","v.","感覺",1,"I feel happy today.","我今天感到快樂。"],
  ["find","v.","找到",1,"I can't find my keys.","我找不到我的鑰匙。"],
  ["fish","n./v.","魚/釣魚",1,"He likes to go fishing.","他喜歡去釣魚。"],
  ["flower","n.","花",1,"She planted flowers in the garden.","她在花園裡種了花。"],
  ["fly","v.","飛",1,"Birds fly south in winter.","冬天鳥往南飛。"],
  ["food","n.","食物",1,"Taiwan has delicious food.","台灣有美味的食物。"],
  ["forget","v.","忘記",1,"Don't forget to lock the door.","不要忘記鎖門。"],
  ["friendly","adj.","友善的",1,"Our new teacher is very friendly.","我們的新老師非常友善。"],
  ["fun","n./adj.","樂趣/有趣的",1,"Swimming is so much fun.","游泳真的很有趣。"],
  ["get","v.","得到",1,"I need to get some rest.","我需要休息一下。"],
  ["girl","n.","女孩",1,"The girl smiled shyly.","那個女孩靦腆地微笑。"],
  ["give","v.","給",1,"Give me your hand.","給我你的手。"],
  ["go","v.","去",1,"Let's go to the park.","我們去公園吧。"],
  ["good","adj.","好的",1,"Have a good time!","玩得開心！"],
  ["green","adj./n.","綠色的",1,"The grass is green.","草是綠色的。"],
  ["grow","v.","成長",1,"Children grow so fast.","孩子們長得好快。"],
  ["hand","n./v.","手/遞給",1,"Hold my hand.","握住我的手。"],
  ["happy","adj.","快樂的",1,"She is always happy.","她總是很快樂。"],
  ["have","v.","有/吃",1,"I have two sisters.","我有兩個姐妹。"],
  ["help","v./n.","幫助",1,"Can you help me?","你能幫助我嗎？"],
  ["here","adv.","在這裡",1,"Come here!","到這裡來！"],
  ["high","adj.","高的",1,"The mountain is very high.","這座山非常高。"],
  ["home","n.","家",1,"There's no place like home.","沒有地方像家一樣。"],
  ["hope","n./v.","希望",1,"Never lose hope.","永遠不要失去希望。"],
  ["hot","adj.","熱的",1,"It is very hot in summer.","夏天非常熱。"],
  ["house","n.","房子",1,"They live in a big house.","他們住在一棟大房子裡。"],
  ["idea","n.","想法",1,"That's a great idea!","那是個很好的主意！"],
  ["interest","n./v.","興趣",1,"Develop an interest in reading.","培養對閱讀的興趣。"],
  ["just","adv.","只是/剛剛",1,"I just finished my homework.","我剛完成作業。"],
  ["keep","v.","保持/保留",1,"Keep your room clean.","保持你的房間整潔。"],
  ["kind","adj./n.","善良的/種類",1,"Be kind to everyone.","對每個人都要善良。"],
  ["know","v.","知道/認識",1,"Do you know the answer?","你知道答案嗎？"],
  ["large","adj.","大的",1,"They live in a large apartment.","他們住在一個大公寓裡。"],
  ["last","adj./v.","最後的/持續",1,"This is our last chance.","這是我們最後的機會。"],
  ["laugh","v./n.","笑",1,"Laughter is the best medicine.","笑是最好的藥。"],
  ["learn","v.","學習",1,"We learn from our mistakes.","我們從錯誤中學習。"],
  ["leave","v.","離開/留下",1,"We must leave now.","我們現在必須離開。"],
  ["life","n.","生命/生活",1,"Life is full of surprises.","生活充滿驚喜。"],
  ["light","n./adj.","光/輕的",1,"Turn on the light.","把燈打開。"],
  ["like","v./prep.","喜歡/像",1,"I like chocolate ice cream.","我喜歡巧克力冰淇淋。"],
  ["listen","v.","聆聽",1,"Listen carefully to the teacher.","仔細聽老師說話。"],
  ["little","adj.","小的/少的",1,"A little kindness goes a long way.","一點點善意大有用處。"],
  ["live","v.","生活/居住",1,"Where do you live?","你住在哪裡？"],
  ["long","adj.","長的",1,"It was a long journey.","那是一段漫長的旅程。"],
  ["look","v.","看/看起來",1,"Look at the stars!","看那些星星！"],
  ["love","n./v.","愛",1,"Love is the greatest gift.","愛是最偉大的禮物。"],
  ["make","v.","製作/使得",1,"Let's make a cake.","我們來做蛋糕吧。"],
  ["man","n.","男人/人類",1,"He is a kind man.","他是一個善良的男人。"],
  ["many","adj.","許多",1,"There are many stars in the sky.","天空中有許多星星。"],
  ["meet","v.","見面/遇見",1,"Nice to meet you.","很高興見到你。"],
  ["money","n.","錢",1,"Money can't buy happiness.","錢買不到幸福。"],
  ["morning","n.","早上",1,"Good morning!","早上好！"],
  ["mother","n.","母親",1,"My mother is a teacher.","我的母親是老師。"],
  ["name","n./v.","名字/命名",1,"What is your name?","你叫什麼名字？"],
  ["need","v./n.","需要",1,"We need to talk.","我們需要談談。"],
  ["new","adj.","新的",1,"I bought a new jacket.","我買了一件新夾克。"],
  ["next","adj./adv.","下一個",1,"Who is next?","下一個是誰？"],
  ["night","n.","夜晚",1,"Good night!","晚安！"],
  ["now","adv.","現在",1,"Do it now!","現在就做！"],
  ["old","adj.","老的/舊的",1,"My grandfather is very old.","我的祖父非常年老。"],
  ["open","adj./v.","開著的/打開",1,"Open the window.","打開窗戶。"],
  ["own","adj./v.","自己的/擁有",1,"Everyone needs their own space.","每個人都需要自己的空間。"],
  ["park","n./v.","公園/停車",1,"The children play in the park.","孩子們在公園裡玩耍。"],
  ["people","n.","人們",1,"People come from all over the world.","人們來自世界各地。"],
  ["place","n./v.","地方/放置",1,"This is a beautiful place.","這是一個美麗的地方。"],
  ["plan","n./v.","計劃",1,"Plan your day the night before.","前一晚計畫好隔天的行程。"],
  ["play","v./n.","玩/戲劇",1,"Children love to play.","孩子們喜歡玩耍。"],
  ["please","v./adv.","請/取悅",1,"Please sit down.","請坐下。"],
  ["point","n./v.","點/指出",1,"That's a good point.","那是個好論點。"],
  ["problem","n.","問題",1,"Every problem has a solution.","每個問題都有解決方法。"],
  ["put","v.","放",1,"Put the book on the shelf.","把書放在書架上。"],
  ["read","v.","閱讀",1,"I read before going to bed.","我睡前閱讀。"],
  ["red","adj./n.","紅色的",1,"She wore a red dress.","她穿了一件紅色洋裝。"],
  ["remember","v.","記住",1,"Remember to bring your homework.","記得帶你的作業。"],
  ["right","adj./n.","正確的/右邊",1,"Turn right at the corner.","在轉角右轉。"],
  ["run","v.","跑",1,"She runs every morning.","她每天早上跑步。"],
  ["same","adj.","相同的",1,"We have the same birthday.","我們的生日相同。"],
  ["save","v.","拯救/儲存",1,"Save your work before you close.","關閉前記得儲存你的工作。"],
  ["say","v.","說",1,"What did she say?","她說了什麼？"],
  ["school","n.","學校",1,"I love going to school.","我喜歡上學。"],
  ["see","v.","看見",1,"See you tomorrow!","明天見！"],
  ["short","adj.","短的/矮的",1,"The movie was too short.","這部電影太短了。"],
  ["show","v./n.","展示/節目",1,"Show me your homework.","把你的作業給我看。"],
  ["sister","n.","姐妹",1,"My sister is a doctor.","我的姐姐是醫生。"],
  ["sit","v.","坐",1,"Please sit down.","請坐下。"],
  ["sleep","v./n.","睡覺",1,"Get enough sleep every night.","每晚要睡足夠的覺。"],
  ["small","adj.","小的",1,"She has a small dog.","她有一隻小狗。"],
  ["smile","v./n.","微笑",1,"A smile can brighten someone's day.","微笑可以讓別人的一天更美好。"],
  ["speak","v.","說話",1,"Speak up! I can't hear you.","說大聲一點！我聽不到你。"],
  ["stand","v.","站立",1,"Stand up straight.","站直。"],
  ["start","v.","開始",1,"Let's start the meeting.","我們開始會議吧。"],
  ["still","adj./adv.","靜止的/仍然",1,"She still loves him.","她仍然愛他。"],
  ["stop","v.","停止",1,"Stop talking and listen.","停止說話，好好聽。"],
  ["strong","adj.","強壯的",1,"He is a strong person.","他是一個強壯的人。"],
  ["student","n.","學生",1,"She is an excellent student.","她是一名優秀的學生。"],
  ["swim","v.","游泳",1,"I can swim very well.","我游泳游得很好。"],
  ["table","n.","桌子",1,"Put the dishes on the table.","把碗盤放在桌子上。"],
  ["take","v.","拿/乘坐",1,"Take the first turn on the left.","在第一個路口向左轉。"],
  ["talk","v./n.","說話/談話",1,"Let's talk about it later.","我們待會兒再談吧。"],
  ["tall","adj.","高的",1,"He is tall for his age.","他對他的年齡來說很高。"],
  ["teach","v.","教",1,"She teaches English.","她教英語。"],
  ["tell","v.","告訴",1,"Tell me the truth.","告訴我真相。"],
  ["thank","v.","感謝",1,"Thank you for your help.","感謝你的幫助。"],
  ["think","v.","思考",1,"Think before you speak.","說話前先思考。"],
  ["time","n.","時間",1,"Time flies when you're having fun.","快樂時光過得特別快。"],
  ["today","n./adv.","今天",1,"Today is a great day.","今天是美好的一天。"],
  ["together","adv.","一起",1,"Let's do it together.","我們一起做吧。"],
  ["tree","n.","樹",1,"The tree is very old.","這棵樹很老了。"],
  ["true","adj.","真實的",1,"Is that story true?","那個故事是真的嗎？"],
  ["try","v.","嘗試",1,"Try your best!","盡力而為！"],
  ["understand","v.","理解",1,"Do you understand the question?","你理解這個問題嗎？"],
  ["use","v./n.","使用",1,"Use a pencil, not a pen.","用鉛筆，不要用鋼筆。"],
  ["very","adv.","非常",1,"I am very happy.","我非常高興。"],
  ["walk","v./n.","走路",1,"Let's take a walk in the park.","我們在公園裡散步吧。"],
  ["want","v.","想要",1,"I want to learn English.","我想學英語。"],
  ["watch","v./n.","看/手錶",1,"Watch TV after dinner.","晚飯後看電視。"],
  ["water","n.","水",1,"Drink eight glasses of water a day.","每天喝八杯水。"],
  ["way","n.","方法/路",1,"There is always a way.","總是有辦法的。"],
  ["well","adv./adj.","好/健康",1,"She speaks English very well.","她說英語說得非常好。"],
  ["what","pron./adj.","什麼",1,"What is your name?","你叫什麼名字？"],
  ["when","adv./conj.","當...時候",1,"Call me when you arrive.","到了打電話給我。"],
  ["where","adv.","哪裡",1,"Where are you from?","你來自哪裡？"],
  ["white","adj./n.","白色的",1,"She wore a white shirt.","她穿了一件白色襯衫。"],
  ["who","pron.","誰",1,"Who is your best friend?","你最好的朋友是誰？"],
  ["why","adv.","為什麼",1,"Why are you late?","你為什麼遲到？"],
  ["woman","n.","女人",1,"She is a strong woman.","她是一個堅強的女人。"],
  ["wonderful","adj.","精彩的",1,"What a wonderful day!","多美好的一天啊！"],
  ["work","n./v.","工作",1,"Hard work always pays off.","努力工作總是會有回報的。"],
  ["world","n.","世界",1,"Travel around the world.","環遊世界。"],
  ["write","v.","寫",1,"Write your name on the paper.","在紙上寫下你的名字。"],
  ["year","n.","年",1,"Happy New Year!","新年快樂！"],
  ["young","adj.","年輕的",1,"She looks young for her age.","她看起來比實際年齡年輕。"],

  // ── Level 2 ──────────────────────────────────────────────────────────────
  ["ability","n.","能力",2,"He has the ability to learn quickly.","他有快速學習的能力。"],
  ["absent","adj.","缺席的",2,"He was absent from school today.","他今天沒來上學。"],
  ["abroad","adv.","在國外",2,"She studied abroad for two years.","她在國外讀了兩年書。"],
  ["accept","v.","接受",2,"Please accept my apology.","請接受我的道歉。"],
  ["accident","n.","意外",2,"There was a car accident on the road.","路上發生了一起車禍。"],
  ["active","adj.","積極的",2,"Stay active to keep healthy.","保持積極以維持健康。"],
  ["address","n./v.","地址/演講",2,"What is your address?","你的地址是什麼？"],
  ["advance","n./v.","進步/前進",2,"Technology advances every year.","科技每年都在進步。"],
  ["ago","adv.","以前",2,"He left ten minutes ago.","他十分鐘前離開了。"],
  ["aid","n./v.","幫助",2,"First aid can save lives.","急救能救人性命。"],
  ["aim","n./v.","目標/瞄準",2,"My aim is to pass the exam.","我的目標是通過考試。"],
  ["alarm","n./v.","警報",2,"The fire alarm went off suddenly.","火警突然響起。"],
  ["alike","adj./adv.","相似的",2,"The twins look alike.","這對雙胞胎長得很像。"],
  ["alive","adj.","活著的",2,"Luckily, everyone was alive.","幸運地，每個人都活著。"],
  ["although","conj.","雖然",2,"Although it rained, we had fun.","雖然下雨，我們還是玩得很開心。"],
  ["amount","n./v.","數量/合計",2,"A large amount of water is wasted daily.","每天大量的水被浪費。"],
  ["ancient","adj.","古老的",2,"The temple is ancient.","這座廟宇很古老。"],
  ["ankle","n.","腳踝",2,"She twisted her ankle.","她扭傷了腳踝。"],
  ["apartment","n.","公寓",2,"She lives in a small apartment.","她住在一間小公寓裡。"],
  ["appearance","n.","外觀/出現",2,"First impressions are based on appearance.","第一印象是基於外表的。"],
  ["appetite","n.","食慾",2,"Exercise increases your appetite.","運動會增加你的食慾。"],
  ["apply","v.","申請/應用",2,"I plan to apply to university.","我計劃申請大學。"],
  ["arrange","v.","安排",2,"Can you arrange a meeting?","你能安排一次會議嗎？"],
  ["arrest","v./n.","逮捕",2,"The police arrested the thief.","警察逮捕了小偷。"],
  ["arrive","v.","到達",2,"The train arrives at 8 p.m.","火車晚上八點到達。"],
  ["aside","adv.","在旁邊",2,"Step aside, please.","請讓一讓。"],
  ["asleep","adj.","睡著的",2,"The baby fell asleep quickly.","嬰兒很快就睡著了。"],
  ["assistant","n.","助理",2,"She is the manager's assistant.","她是經理的助理。"],
  ["attack","v./n.","攻擊",2,"The dog attacked the stranger.","那隻狗攻擊了陌生人。"],
  ["attend","v.","出席",2,"All students must attend class.","所有學生都必須上課。"],
  ["attention","n.","注意力",2,"Pay attention in class.","上課要注意聽。"],
  ["avoid","v.","避免",2,"Try to avoid eating junk food.","盡量避免吃垃圾食物。"],
  ["award","n./v.","獎項",2,"She won an award for her work.","她因工作出色而獲獎。"],
  ["aware","adj.","意識到的",2,"Be aware of your surroundings.","要注意你周圍的環境。"],
  ["awful","adj.","可怕的",2,"The weather was awful.","天氣很糟糕。"],
  ["base","n./v.","基礎/以...為基礎",2,"The movie is based on a true story.","這部電影基於真實故事。"],
  ["basic","adj.","基本的",2,"Learn the basic rules first.","先學習基本規則。"],
  ["bear","v.","承受/忍受",2,"I can't bear the heat.","我受不了這種熱。"],
  ["beat","v./n.","擊打/節拍",2,"Her heart beat with excitement.","她的心因興奮而跳動。"],
  ["beauty","n.","美",2,"Beauty is in the eye of the beholder.","情人眼裡出西施。"],
  ["behave","v.","表現",2,"Please behave yourself in class.","請在課堂上注意行為。"],
  ["believe","v.","相信",2,"I believe you can do it.","我相信你能做到。"],
  ["benefit","n./v.","好處",2,"Exercise has many health benefits.","運動對健康有許多好處。"],
  ["brave","adj.","勇敢的",2,"She was brave enough to speak up.","她勇敢地站出來說話。"],
  ["breathe","v.","呼吸",2,"Take a moment to breathe deeply.","花點時間深呼吸。"],
  ["calm","adj./v.","冷靜的",2,"Stay calm during the test.","考試時保持冷靜。"],
  ["cause","n./v.","原因/導致",2,"Pollution causes serious harm to health.","污染對健康造成嚴重傷害。"],
  ["complete","adj./v.","完整的/完成",2,"Please complete the form.","請填寫表格。"],
  ["consider","v.","考慮",2,"Please consider my offer.","請考慮我的提議。"],
  ["control","n./v.","控制",2,"Keep your emotions under control.","保持情緒受控。"],
  ["create","v.","創造",2,"Artists create beauty with their work.","藝術家用作品創造美。"],
  ["decide","v.","決定",2,"It's hard to decide between two choices.","在兩個選擇之間做決定很難。"],
  ["depend","v.","依賴",2,"Young children depend on their parents.","小孩子依賴他們的父母。"],
  ["describe","v.","描述",2,"Can you describe what happened?","你能描述一下發生了什麼嗎？"],
  ["develop","v.","發展",2,"We develop new habits over time.","我們隨著時間發展出新習慣。"],
  ["discover","v.","發現",2,"Scientists discover new things every day.","科學家每天都在發現新事物。"],
  ["discuss","v.","討論",2,"Let's discuss the plan.","我們來討論計畫吧。"],
  ["earn","v.","賺得",2,"You earn respect through your actions.","你透過行動贏得尊重。"],
  ["effort","n.","努力",2,"Success requires consistent effort.","成功需要持續的努力。"],
  ["experience","n./v.","經驗",2,"Travel gives you valuable experience.","旅行給你寶貴的經驗。"],
  ["explain","v.","解釋",2,"Can you explain this to me again?","你能再解釋一遍嗎？"],
  ["express","v.","表達",2,"Express your feelings clearly.","清楚地表達你的感受。"],
  ["fail","v.","失敗",2,"Don't be afraid to fail and try again.","不要怕失敗，再接再厲。"],
  ["famous","adj.","著名的",2,"Taiwan is famous for its night markets.","台灣以夜市聞名。"],
  ["foreign","adj.","外國的",2,"She can speak three foreign languages.","她能說三門外語。"],
  ["future","n./adj.","未來",2,"Plan for the future.","為未來做計劃。"],
  ["goal","n.","目標",2,"Set a clear goal for yourself.","為自己設定一個清晰的目標。"],
  ["guess","v./n.","猜測",2,"Can you guess the answer?","你能猜出答案嗎？"],
  ["healthy","adj.","健康的",2,"Eat healthy food every day.","每天吃健康的食物。"],
  ["honest","adj.","誠實的",2,"Be honest even when it's difficult.","即使困難，也要誠實。"],
  ["imagine","v.","想像",2,"Imagine a world without pollution.","想像一個沒有污染的世界。"],
  ["improve","v.","改善",2,"Practice daily to improve your skills.","每天練習以提升你的技能。"],
  ["include","v.","包括",2,"The price includes tax.","價格包含稅。"],
  ["information","n.","資訊",2,"I need more information.","我需要更多資訊。"],
  ["introduce","v.","介紹",2,"Let me introduce myself.","讓我介紹我自己。"],
  ["knowledge","n.","知識",2,"Knowledge is power.","知識就是力量。"],
  ["leader","n.","領袖",2,"She is a natural leader.","她是天生的領袖。"],
  ["local","adj.","當地的",2,"Support local businesses.","支持當地商家。"],
  ["matter","n./v.","事情/重要",2,"Every little thing matters.","每一件小事都很重要。"],
  ["memory","n.","記憶",2,"I have a great memory for faces.","我對面孔有很強的記憶力。"],
  ["modern","adj.","現代的",2,"We live in a modern world.","我們生活在一個現代世界。"],
  ["necessary","adj.","必要的",2,"Sleep is necessary for good health.","睡眠對健康來說是必要的。"],
  ["nervous","adj.","緊張的",2,"I felt nervous before the speech.","演講前我感到緊張。"],
  ["patient","adj./n.","耐心的/病人",2,"Be patient; good things take time.","要有耐心，好事需要時間。"],
  ["promise","n./v.","承諾",2,"Always keep your promises.","永遠遵守你的承諾。"],
  ["protect","v.","保護",2,"We must protect our oceans.","我們必須保護我們的海洋。"],
  ["provide","v.","提供",2,"Libraries provide free access to books.","圖書館免費提供書籍。"],
  ["realize","v.","意識到",2,"I realized I had made a mistake.","我意識到我犯了一個錯誤。"],
  ["reason","n.","理由",2,"Give me a good reason to trust you.","給我一個信任你的好理由。"],
  ["respect","n./v.","尊重",2,"Respect is earned, not given.","尊重是贏得的，不是給予的。"],
  ["result","n.","結果",2,"The results surprised everyone.","結果讓所有人感到驚訝。"],
  ["review","v./n.","複習/評論",2,"Review your notes before the exam.","考試前複習你的筆記。"],
  ["serious","adj.","嚴肅的/嚴重的",2,"This is a serious situation.","這是一個嚴峻的情況。"],
  ["share","v./n.","分享",2,"Share what you know with others.","把你知道的東西與他人分享。"],
  ["skill","n.","技能",2,"Communication is a vital skill.","溝通是一項重要技能。"],
  ["solve","v.","解決",2,"We need to solve this together.","我們需要一起解決這個問題。"],
  ["support","n./v.","支持",2,"Thank you for your support.","感謝你的支持。"],
  ["trust","n./v.","信任",2,"Trust is the foundation of friendship.","信任是友誼的基礎。"],
  ["truth","n.","真相",2,"Always tell the truth.","永遠說實話。"],
  ["value","n./v.","價值",2,"Family values are very important.","家庭價值觀非常重要。"],

  // ── Level 3 ──────────────────────────────────────────────────────────────
  ["achieve","v.","達成",3,"Hard work helps you achieve your dreams.","努力幫助你實現夢想。"],
  ["activity","n.","活動",3,"Outdoor activities are good for kids.","戶外活動對孩子們有益。"],
  ["admire","v.","欽佩",3,"I admire her courage.","我欽佩她的勇氣。"],
  ["admit","v.","承認",3,"He finally admitted the truth.","他終於承認了事實。"],
  ["adopt","v.","採用/收養",3,"They decided to adopt a puppy.","他們決定收養一隻小狗。"],
  ["advice","n.","建議",3,"Let me give you some advice.","讓我給你一些建議。"],
  ["advise","v.","建議",3,"I advise you to see a doctor.","我建議你去看醫生。"],
  ["affect","v.","影響",3,"Weather affects our mood.","天氣影響我們的情緒。"],
  ["afford","v.","負擔得起",3,"I can't afford a new phone.","我買不起新手機。"],
  ["agriculture","n.","農業",3,"Agriculture feeds the world.","農業養活了整個世界。"],
  ["amaze","v.","使驚奇",3,"Her performance amazed everyone.","她的表演讓所有人驚嘆。"],
  ["ambition","n.","野心/抱負",3,"He has the ambition to become a doctor.","他有成為醫生的抱負。"],
  ["announce","v.","宣布",3,"The teacher announced the test date.","老師宣布了考試日期。"],
  ["appear","v.","出現",3,"Stars appear at night.","星星在夜晚出現。"],
  ["appreciate","v.","感激/欣賞",3,"I appreciate your help very much.","我非常感激你的幫助。"],
  ["approve","v.","批准/贊同",3,"The boss approved the plan.","老闆批准了計劃。"],
  ["aspect","n.","方面",3,"Consider every aspect of the problem.","考慮問題的每個方面。"],
  ["assist","v.","協助",3,"The nurse assisted the doctor.","護士協助了醫生。"],
  ["athlete","n.","運動員",3,"She trained hard to become an athlete.","她努力訓練以成為運動員。"],
  ["atmosphere","n.","大氣/氣氛",3,"The atmosphere in the hall was exciting.","大廳裡的氣氛令人興奮。"],
  ["attempt","v./n.","嘗試",3,"This is my first attempt at cooking.","這是我第一次嘗試做飯。"],
  ["balance","n./v.","平衡",3,"Work-life balance is important.","工作與生活的平衡很重要。"],
  ["career","n.","職業生涯",3,"Choose a career you are passionate about.","選擇你熱愛的職業。"],
  ["celebrate","v.","慶祝",3,"We celebrate the New Year with fireworks.","我們用煙火慶祝新年。"],
  ["challenge","n./v.","挑戰",3,"Every challenge is a chance to grow.","每一個挑戰都是成長的機會。"],
  ["communicate","v.","溝通",3,"It's important to communicate clearly.","清楚地溝通是很重要的。"],
  ["compete","v.","競爭",3,"Students compete for top grades.","學生們競相爭取高分。"],
  ["concern","n./v.","擔心/關切",3,"I'm concerned about your health.","我擔心你的健康。"],
  ["confident","adj.","有信心的",3,"Be confident when you speak in public.","公開演講時要有自信。"],
  ["courage","n.","勇氣",3,"It takes courage to admit a mistake.","承認錯誤需要勇氣。"],
  ["curious","adj.","好奇的",3,"Children are naturally curious.","孩子天生就充滿好奇心。"],
  ["danger","n.","危險",3,"The hiker was in danger of falling.","登山者有跌倒的危險。"],
  ["define","v.","定義",3,"Can you define this word?","你能定義這個詞嗎？"],
  ["demand","n./v.","需求/要求",3,"There is high demand for good teachers.","對優秀教師的需求很高。"],
  ["duty","n.","責任",3,"It's our duty to protect the environment.","保護環境是我們的責任。"],
  ["educate","v.","教育",3,"Education can change a person's life.","教育可以改變一個人的人生。"],
  ["emotion","n.","情感",3,"Music can trigger strong emotions.","音樂能觸發強烈的情感。"],
  ["encourage","v.","鼓勵",3,"Parents should encourage their children.","父母應該鼓勵孩子。"],
  ["environment","n.","環境",3,"We must protect our environment.","我們必須保護我們的環境。"],
  ["equal","adj.","平等的",3,"Everyone deserves equal rights.","每個人都應該享有平等的權利。"],
  ["escape","v./n.","逃跑",3,"The bird escaped from its cage.","那隻鳥從籠子裡逃了出去。"],
  ["examine","v.","檢查/考試",3,"The doctor examined the patient.","醫生檢查了病人。"],
  ["focus","n./v.","專注",3,"Focus on one thing at a time.","一次專注於一件事。"],
  ["freedom","n.","自由",3,"Everyone deserves freedom of speech.","每個人都應享有言論自由。"],
  ["function","n./v.","功能",3,"What is the function of this button?","這個按鈕的功能是什麼？"],
  ["government","n.","政府",3,"The government announced new policies.","政府宣布了新政策。"],
  ["guide","n./v.","指導/嚮導",3,"She guided us through the museum.","她帶領我們參觀博物館。"],
  ["habit","n.","習慣",3,"Reading is a good habit to develop.","閱讀是一個值得培養的好習慣。"],
  ["handle","v./n.","處理/把手",3,"How do you handle stress?","你如何應對壓力？"],
  ["harm","n./v.","傷害",3,"Smoking can harm your lungs.","吸菸會傷害你的肺。"],
  ["independent","adj.","獨立的",3,"She became independent at an early age.","她很早就獨立了。"],
  ["influence","n./v.","影響",3,"Parents have a great influence on children.","父母對孩子有很大的影響。"],
  ["involve","v.","涉及/包含",3,"The plan involves many steps.","這個計劃包含許多步驟。"],
  ["judge","v./n.","判斷/法官",3,"Don't judge others too quickly.","不要太快評判別人。"],
  ["limit","n./v.","限制",3,"There is a time limit for the test.","考試有時間限制。"],
  ["manage","v.","管理",3,"She manages her time very well.","她把時間管理得非常好。"],
  ["mention","v.","提及",3,"Did you mention the meeting?","你有提到會議嗎？"],
  ["method","n.","方法",3,"What method do you use?","你用什麼方法？"],
  ["opportunity","n.","機會",3,"Don't miss this great opportunity.","不要錯過這個好機會。"],
  ["organize","v.","組織",3,"Organize your notes after class.","課後整理你的筆記。"],
  ["original","adj.","原創的/最初的",3,"This is an original painting.","這是一幅原創畫作。"],
  ["perform","v.","執行/表演",3,"She performed beautifully on stage.","她在台上表演得非常漂亮。"],
  ["positive","adj.","正面的",3,"Keep a positive attitude every day.","每天保持積極的態度。"],
  ["prepare","v.","準備",3,"Prepare well before the exam.","考試前充分準備。"],
  ["prevent","v.","預防",3,"Wash your hands to prevent illness.","洗手以預防疾病。"],
  ["purpose","n.","目的",3,"What is the purpose of this project?","這個計劃的目的是什麼？"],
  ["recognize","v.","認識/認可",3,"I didn't recognize her at first.","我起初沒認出她。"],
  ["reduce","v.","減少",3,"We should reduce waste every day.","我們每天都應該減少浪費。"],
  ["relationship","n.","關係",3,"She has a good relationship with her boss.","她和老闆的關係很好。"],
  ["responsibility","n.","責任",3,"Taking responsibility shows maturity.","承擔責任體現成熟。"],
  ["risk","n./v.","風險",3,"Every decision carries some risk.","每個決定都帶有一些風險。"],
  ["situation","n.","情況",3,"The situation is under control.","情況在掌控之中。"],
  ["society","n.","社會",3,"We all live in society.","我們都生活在社會中。"],
  ["talent","n.","才能",3,"She has a talent for music.","她有音樂才能。"],
  ["technology","n.","科技",3,"Technology changes how we live.","科技改變了我們的生活方式。"],
  ["tradition","n.","傳統",3,"Every culture has its own traditions.","每種文化都有自己的傳統。"],
  ["unique","adj.","獨特的",3,"Everyone is unique in their own way.","每個人都有自己獨特的地方。"],
  ["variety","n.","多樣性/種類",3,"There is a great variety of food here.","這裡有很多種類的食物。"],
  ["volunteer","n./v.","志願者/自願",3,"She volunteers at the hospital.","她在醫院當志工。"],

  // ── Level 4 ──────────────────────────────────────────────────────────────
  ["abandon","v.","放棄",4,"She had to abandon her car in the snow.","她不得不將車子遺棄在雪地裡。"],
  ["absolute","adj.","絕對的",4,"The law requires absolute honesty.","法律要求絕對誠實。"],
  ["absorb","v.","吸收",4,"Plants absorb sunlight to make energy.","植物吸收陽光來製造能量。"],
  ["abstract","adj.","抽象的",4,"Love is an abstract concept.","愛是個抽象概念。"],
  ["academic","adj.","學術的",4,"She has a strong academic record.","她有優秀的學術成績。"],
  ["accompany","v.","陪伴",4,"She accompanied him to the hospital.","她陪他去醫院。"],
  ["accomplish","v.","完成",4,"We accomplished our goal ahead of time.","我們提前完成了目標。"],
  ["accurate","adj.","準確的",4,"The weather forecast was accurate.","天氣預報很準確。"],
  ["accuse","v.","指控",4,"He was accused of stealing.","他被指控偷竊。"],
  ["acquire","v.","獲得",4,"He acquired a new skill online.","他在網路上習得了一項新技能。"],
  ["adapt","v.","適應",4,"It takes time to adapt to a new city.","適應一座新城市需要時間。"],
  ["adequate","adj.","足夠的",4,"Make sure you get adequate sleep.","確保你有足夠的睡眠。"],
  ["adjust","v.","調整",4,"Please adjust the volume.","請調整音量。"],
  ["aggressive","adj.","好鬥的/積極的",4,"An aggressive approach may backfire.","激進的方式可能適得其反。"],
  ["alert","adj./n./v.","警覺的/警報",4,"Stay alert while driving.","開車時保持警覺。"],
  ["ambitious","adj.","有野心的",4,"She is ambitious and hardworking.","她有野心且勤奮。"],
  ["analyze","v.","分析",4,"We need to analyze the data carefully.","我們需要仔細分析這些資料。"],
  ["annual","adj.","每年的",4,"The annual report is due next week.","年度報告下週到期。"],
  ["anxiety","n.","焦慮",4,"Exam anxiety is very common.","考試焦慮非常普遍。"],
  ["anxious","adj.","焦慮的",4,"She felt anxious about the interview.","她對面試感到焦慮。"],
  ["apologize","v.","道歉",4,"He apologized for being late.","他為遲到而道歉。"],
  ["apology","n.","道歉",4,"She accepted my apology.","她接受了我的道歉。"],
  ["appropriate","adj.","適當的",4,"Wear appropriate clothing for the job.","穿著適合工作的服裝。"],
  ["arise","v.","出現/發生",4,"Problems arise when rules are ignored.","忽視規則時問題就會出現。"],
  ["arrogant","adj.","傲慢的",4,"Don't be arrogant about your success.","不要對你的成功感到傲慢。"],
  ["assemble","v.","集合/組裝",4,"Assemble the furniture carefully.","仔細組裝家具。"],
  ["associate","v./n.","聯繫/同事",4,"I associate the smell with childhood.","我把這種氣味與童年聯繫起來。"],
  ["assume","v.","假設",4,"Don't assume you already know everything.","不要假設你已經什麼都知道。"],
  ["assure","v.","保證",4,"I assure you it's safe.","我向你保證這是安全的。"],
  ["attach","v.","附加",4,"Please attach the file to your email.","請把文件附加到你的郵件中。"],
  ["attitude","n.","態度",4,"A positive attitude makes a difference.","積極的態度有很大的作用。"],
  ["attract","v.","吸引",4,"The museum attracts many visitors.","博物館吸引了許多遊客。"],
  ["audience","n.","觀眾",4,"The audience applauded at the end.","觀眾在最後鼓掌。"],
  ["barrier","n.","障礙",4,"Language can be a barrier to learning.","語言可能是學習的障礙。"],
  ["burden","n./v.","負擔",4,"Don't let stress become a burden.","不要讓壓力變成負擔。"],
  ["campaign","n./v.","運動/活動",4,"She ran a successful election campaign.","她進行了一場成功的選舉活動。"],
  ["capable","adj.","有能力的",4,"She is capable of leading the team.","她有能力領導這個團隊。"],
  ["complex","adj.","複雜的",4,"This problem is very complex.","這個問題非常複雜。"],
  ["conflict","n./v.","衝突",4,"Avoid conflict by listening carefully.","仔細聆聽以避免衝突。"],
  ["consequence","n.","後果",4,"Think before you act to avoid bad consequences.","行動前三思以避免不良後果。"],
  ["cooperate","v.","合作",4,"We must cooperate to succeed.","我們必須合作才能成功。"],
  ["grateful","adj.","感激的",4,"I'm grateful for all your support.","我對你所有的支持感到感激。"],
  ["humble","adj.","謙遜的",4,"Stay humble no matter how successful you are.","無論多成功，都要保持謙遜。"],
  ["inspire","v.","激勵",4,"Great leaders inspire others to act.","偉大的領導者激勵他人採取行動。"],
  ["moral","adj./n.","道德的",4,"We must make moral decisions.","我們必須做出道德的決定。"],
  ["motivate","v.","激勵",4,"What motivates you to study?","是什麼激勵你學習？"],
  ["negotiate","v.","談判/協商",4,"They negotiated a lower price.","他們協商出了更低的價格。"],
  ["objective","n./adj.","目標/客觀的",4,"Be objective when making decisions.","做決定時要保持客觀。"],
  ["perceive","v.","感知/察覺",4,"How do you perceive this situation?","你如何看待這種情況？"],
  ["preserve","v.","保存/保護",4,"We must preserve our cultural heritage.","我們必須保護我們的文化遺產。"],
  ["promote","v.","促進/晉升/宣傳",4,"Exercise promotes good health.","運動促進健康。"],
  ["pursue","v.","追求",4,"Pursue your dreams with determination.","以決心追求你的夢想。"],
  ["reliable","adj.","可靠的",4,"He is a reliable friend.","他是個可靠的朋友。"],
  ["resolve","v./n.","解決/決心",4,"We must resolve the conflict peacefully.","我們必須和平解決衝突。"],
  ["restore","v.","恢復/修復",4,"The painting was carefully restored.","這幅畫被仔細修復了。"],
  ["sacrifice","n./v.","犧牲",4,"Parents sacrifice a lot for their children.","父母為孩子犧牲了很多。"],
  ["stable","adj.","穩定的",4,"The economy remains stable.","經濟保持穩定。"],
  ["strategy","n.","策略",4,"We need a new marketing strategy.","我們需要新的行銷策略。"],
  ["struggle","v./n.","掙扎/奮鬥",4,"She struggled to balance work and family.","她努力在工作和家庭之間取得平衡。"],
  ["sufficient","adj.","足夠的",4,"Is the evidence sufficient?","這些證據足夠嗎？"],
  ["wisdom","n.","智慧",4,"Wisdom comes with experience.","智慧隨著經驗而來。"],

  // ── Level 5 ──────────────────────────────────────────────────────────────
  ["absurd","adj.","荒謬的",5,"It's absurd to stay up all night.","徹夜不眠是荒謬的。"],
  ["abundant","adj.","豐富的",5,"Fresh water is abundant in Taiwan.","台灣淡水資源豐富。"],
  ["acknowledge","v.","承認",5,"She acknowledged her mistake.","她承認了自己的錯誤。"],
  ["advocate","v./n.","倡導/倡導者",5,"She advocates for animal rights.","她倡導動物權利。"],
  ["alter","v.","改變",5,"Please don't alter the original document.","請不要修改原始文件。"],
  ["alternate","v./adj.","交替/替代的",5,"They alternate between work and rest.","他們在工作和休息之間交替進行。"],
  ["asset","n.","資產",5,"Education is a valuable asset.","教育是寶貴的資產。"],
  ["astray","adv./adj.","迷途的",5,"Don't let bad friends lead you astray.","不要讓壞朋友引你誤入歧途。"],
  ["astronaut","n.","太空人",5,"She dreamed of becoming an astronaut.","她夢想成為一名太空人。"],
  ["astronomy","n.","天文學",5,"He studies astronomy at university.","他在大學學習天文學。"],
  ["chronic","adj.","慢性的/長期的",5,"She suffers from chronic back pain.","她長期受背痛困擾。"],
  ["cite","v.","引用/列舉",5,"Please cite your sources in the essay.","請在文章中引用你的資料來源。"],
  ["clarify","v.","澄清",5,"Please clarify what you mean.","請澄清你的意思。"],
  ["classify","v.","分類",5,"Classify the books by subject.","依主題將書分類。"],
  ["collapse","v./n.","倒塌/崩潰",5,"The building collapsed in the earthquake.","這棟建築在地震中倒塌了。"],
  ["compensate","v.","補償",5,"The company compensated the workers.","公司補償了工人。"],
  ["compose","v.","創作/組成",5,"He composed a beautiful symphony.","他創作了一首美麗的交響樂。"],
  ["condemn","v.","譴責",5,"We condemn violence of any kind.","我們譴責任何形式的暴力。"],
  ["confuse","v.","混淆/迷惑",5,"Don't confuse the two words.","不要混淆這兩個詞。"],
  ["consent","n./v.","同意",5,"You need parental consent.","你需要父母的同意。"],
  ["construct","v.","建造",5,"They are constructing a new bridge.","他們正在建造一座新橋。"],
  ["dedicate","v.","奉獻/獻給",5,"She dedicated her life to science.","她將一生奉獻給科學。"],
  ["desperate","adj.","絕望的",5,"He was desperate for help.","他迫切需要幫助。"],
  ["elaborate","adj./v.","詳盡的/詳述",5,"Can you elaborate on that point?","你能詳細說明那一點嗎？"],
  ["eliminate","v.","消除/淘汰",5,"Eliminate distractions while studying.","學習時消除干擾。"],
  ["emphasize","v.","強調",5,"She emphasized the importance of teamwork.","她強調了團隊合作的重要性。"],
  ["endure","v.","忍受/持久",5,"He endured years of hardship.","他忍受了多年的艱辛。"],
  ["enforce","v.","執行/強制",5,"The police enforce the law.","警察執行法律。"],
  ["estimate","v./n.","估計",5,"Please estimate the cost.","請估計費用。"],
  ["exaggerate","v.","誇大",5,"Don't exaggerate the problem.","不要誇大問題。"],
  ["exhibit","v./n.","展示/展覽",5,"The museum exhibits ancient artifacts.","博物館展示古代文物。"],
  ["extraordinary","adj.","非凡的",5,"She has extraordinary talent.","她有非凡的才能。"],
  ["flexible","adj.","靈活的",5,"Stay flexible in your schedule.","在你的日程安排上保持靈活。"],
  ["fluent","adj.","流利的",5,"She is fluent in three languages.","她能流利地說三種語言。"],
  ["frequent","adj.","頻繁的",5,"He is a frequent visitor to the library.","他是圖書館的常客。"],
  ["frustrate","v.","挫敗/使沮喪",5,"Traffic jams frustrate commuters.","交通堵塞讓通勤者感到沮喪。"],
  ["generate","v.","產生/生成",5,"Solar panels generate electricity.","太陽能板產生電力。"],
  ["genuine","adj.","真正的/真誠的",5,"Is that a genuine diamond?","那是真的鑽石嗎？"],
  ["graceful","adj.","優雅的",5,"The dancer moved in a graceful way.","那位舞蹈者動作非常優雅。"],
  ["guarantee","n./v.","保證",5,"I guarantee you will enjoy this movie.","我保證你會喜歡這部電影。"],
  ["hesitate","v.","猶豫",5,"Don't hesitate to ask for help.","不要猶豫，尋求幫助吧。"],
  ["hypothesis","n.","假設/假說",5,"The scientist tested her hypothesis.","科學家測試了她的假說。"],
  ["identical","adj.","完全相同的",5,"The twins wear identical outfits.","這對雙胞胎穿著相同的服裝。"],
  ["ignore","v.","忽視",5,"Don't ignore warning signs.","不要忽視警告信號。"],
  ["illustrate","v.","說明/插圖",5,"Use examples to illustrate your point.","用例子來說明你的觀點。"],
  ["imply","v.","暗示",5,"What does this sentence imply?","這個句子暗示了什麼？"],
  ["impose","v.","強加/征收",5,"New taxes were imposed on luxury goods.","對奢侈品徵收了新稅。"],
  ["inevitable","adj.","不可避免的",5,"Change is inevitable.","改變是不可避免的。"],
  ["inferior","adj.","較差的/下級的",5,"Don't feel inferior to others.","不要覺得自己比別人差。"],
  ["interpret","v.","解釋/口譯",5,"How do you interpret this poem?","你如何解讀這首詩？"],
  ["investigate","v.","調查",5,"The police investigated the crime.","警察調查了犯罪案件。"],
  ["justify","v.","證明...正當/辯解",5,"How do you justify your decision?","你如何為你的決定辯護？"],
  ["magnificent","adj.","壯觀的/宏偉的",5,"The view from the top was magnificent.","從頂部看到的景色壯觀極了。"],
  ["mature","adj./v.","成熟的/成熟",5,"She is very mature for her age.","她對她的年齡來說非常成熟。"],
  ["migrate","v.","遷移",5,"Birds migrate south in winter.","鳥兒在冬天向南遷徙。"],
  ["numerous","adj.","眾多的",5,"Numerous students applied for the scholarship.","眾多學生申請了獎學金。"],
  ["obstacle","n.","障礙",5,"Overcome every obstacle in your path.","克服你道路上的每個障礙。"],
  ["occupy","v.","佔據/從事",5,"Work occupies most of my time.","工作佔據了我大部分的時間。"],
  ["outcome","n.","結果/成果",5,"What was the outcome of the meeting?","會議的結果如何？"],
  ["overwhelm","v.","壓倒/使不知所措",5,"The work overwhelmed her.","工作讓她不知所措。"],
  ["participate","v.","參與",5,"Everyone is encouraged to participate.","鼓勵每個人參與。"],
  ["privilege","n.","特權",5,"Education is a privilege, not a right.","教育是一種特權，而非權利。"],
  ["reluctant","adj.","不情願的",5,"She was reluctant to leave.","她不情願地離開了。"],
  ["remarkable","adj.","非凡的/顯著的",5,"She made a remarkable recovery.","她的恢復令人矚目。"],
  ["substitute","n./v.","替代品/替換",5,"Use honey as a substitute for sugar.","用蜂蜜代替糖。"],
  ["summarize","v.","總結",5,"Please summarize the article.","請總結這篇文章。"],
  ["superior","adj./n.","優越的/上司",5,"Her skills are superior to mine.","她的技能比我優越。"],
  ["survive","v.","生存/倖存",5,"Only the strong survive.","只有強者才能生存。"],
  ["suspect","v./n.","懷疑/嫌疑人",5,"I suspect he is hiding something.","我懷疑他在隱瞞什麼。"],
  ["sustain","v.","維持/支撐",5,"Sustain your efforts to achieve the goal.","維持你的努力以實現目標。"],
  ["tackle","v./n.","處理/解決",5,"Let's tackle this problem together.","讓我們一起解決這個問題。"],
  ["tendency","n.","傾向",5,"She has a tendency to be late.","她有遲到的傾向。"],
  ["transform","v.","改變/轉化",5,"Exercise can transform your body.","鍛煉可以改變你的身體。"],
  ["trigger","v./n.","觸發",5,"What triggered your interest in science?","是什麼激發了你對科學的興趣？"],
  ["triumph","n./v.","勝利",5,"It was a triumph of will.","這是意志力的勝利。"],
  ["universal","adj.","普遍的/全球的",5,"Music is a universal language.","音樂是一種普世語言。"],
  ["urgent","adj.","緊急的",5,"This is an urgent matter.","這是一件緊急的事。"],
  ["vague","adj.","模糊的",5,"His answer was vague.","他的回答很模糊。"],
  ["vulnerable","adj.","脆弱的/易受傷的",5,"Children are vulnerable to illness.","孩子容易生病。"],

  // ── Level 6 ──────────────────────────────────────────────────────────────
  ["abbreviate","v.","縮寫",6,"We abbreviate 'United Nations' as 'UN'.","我們把「聯合國」縮寫為「UN」。"],
  ["abnormal","adj.","異常的",6,"Abnormal behavior should be reported.","異常行為應該被舉報。"],
  ["abolish","v.","廢除",6,"Slavery was abolished in the 19th century.","奴隸制度在19世紀被廢除。"],
  ["aboriginal","adj./n.","原住民的/原住民",6,"Taiwan has many aboriginal cultures.","台灣有許多原住民文化。"],
  ["accelerate","v.","加速",6,"The car accelerated past the limit.","這輛車超速加速行駛。"],
  ["alternative","adj./n.","替代的/替代方案",6,"We need an alternative solution.","我們需要一個替代方案。"],
  ["ambiguous","adj.","模糊的/有歧義的",6,"The message was ambiguous.","這條訊息是模糊的。"],
  ["analogy","n.","類比/比喻",6,"He used an analogy to explain the concept.","他用類比來解釋這個概念。"],
  ["anticipate","v.","預期/期待",6,"We anticipate a large crowd.","我們預計會有大批人群。"],
  ["apprentice","n./v.","學徒",6,"He started as an apprentice carpenter.","他從木匠學徒開始。"],
  ["approximate","adj./v.","大約的/接近",6,"The approximate cost is 500 dollars.","大約的費用是500美元。"],
  ["articulate","adj./v.","清楚表達的/表達",6,"She articulated her ideas clearly.","她清楚地表達了她的想法。"],
  ["aspire","v.","渴望/立志",6,"She aspires to become a surgeon.","她立志成為一名外科醫生。"],
  ["assert","v.","聲稱/堅持",6,"He asserted his innocence.","他堅持聲稱自己是無辜的。"],
  ["assess","v.","評估",6,"Teachers assess students' progress regularly.","老師定期評估學生的進步。"],
  ["authorize","v.","授權",6,"Who authorized this decision?","誰授權了這個決定？"],
  ["autonomous","adj.","自治的/自主的",6,"The region has autonomous status.","這個地區具有自治地位。"],
  ["bizarre","adj.","奇怪的/古怪的",6,"She wore a bizarre hat.","她戴了一頂奇怪的帽子。"],
  ["captivate","v.","迷住/吸引",6,"The story captivated the audience.","這個故事迷住了觀眾。"],
  ["catastrophe","n.","災難",6,"The flood was a catastrophe for the village.","洪水對村莊來說是一場災難。"],
  ["circulate","v.","流通/傳播",6,"Information circulates quickly online.","資訊在網路上快速傳播。"],
  ["collaborate","v.","合作",6,"Artists collaborate to create new works.","藝術家合作創作新作品。"],
  ["commemorate","v.","紀念",6,"We commemorate the event every year.","我們每年紀念這個事件。"],
  ["compassion","n.","同情心",6,"Show compassion to those in need.","對需要幫助的人表達同情。"],
  ["competent","adj.","有能力的",6,"She is a competent engineer.","她是一名有能力的工程師。"],
  ["comprehend","v.","理解",6,"I couldn't comprehend the theory.","我無法理解這個理論。"],
  ["conceive","v.","構思/懷孕",6,"He conceived a brilliant idea.","他構思了一個絕妙的主意。"],
  ["constitute","v.","構成/組成",6,"What constitutes a crime?","什麼構成犯罪？"],
  ["controversial","adj.","有爭議的",6,"The new law is highly controversial.","這部新法律極具爭議性。"],
  ["cultivate","v.","培養/種植",6,"Cultivate good study habits.","培養良好的學習習慣。"],
  ["cynical","adj.","憤世嫉俗的",6,"He is cynical about politics.","他對政治持憤世嫉俗的態度。"],
  ["debris","n.","碎片/殘骸",6,"Debris covered the road after the storm.","暴風雨後道路上佈滿了碎片。"],
  ["deliberately","adv.","故意地",6,"He deliberately ignored her.","他故意忽視她。"],
  ["depict","v.","描繪",6,"The painting depicts a rural scene.","這幅畫描繪了一個鄉村場景。"],
  ["derive","v.","源自/獲得",6,"This word derives from Latin.","這個詞源自拉丁語。"],
  ["designate","v.","指定/指派",6,"She was designated as team leader.","她被指定為團隊領導。"],
  ["devastate","v.","毀壞/使悲痛",6,"The hurricane devastated the coastline.","颶風摧毀了海岸線。"],
  ["devote","v.","奉獻/投入",6,"He devoted his life to music.","他將一生奉獻給音樂。"],
  ["diagnose","v.","診斷",6,"The doctor diagnosed the illness.","醫生診斷出了疾病。"],
  ["diminish","v.","減少/降低",6,"Her confidence diminished over time.","她的信心隨著時間慢慢降低。"],
  ["distort","v.","扭曲",6,"Media can distort the truth.","媒體可能扭曲事實。"],
  ["diverse","adj.","多樣化的",6,"Our team is very diverse.","我們的團隊非常多元。"],
  ["dominant","adj.","主導的/佔優勢的",6,"English is the dominant global language.","英語是主導的全球語言。"],
  ["dynamic","adj./n.","動態的/動力",6,"The market is always dynamic.","市場始終充滿活力。"],
  ["eloquent","adj.","雄辯的/流暢的",6,"The speaker was eloquent and persuasive.","那位演講者口才流利，很有說服力。"],
  ["emerging","adj.","新興的",6,"AI is an emerging technology.","人工智慧是一項新興技術。"],
  ["erode","v.","侵蝕",6,"The cliffs were eroded by the sea.","懸崖被大海侵蝕了。"],
  ["ethical","adj.","道德的/倫理的",6,"Scientists must follow ethical guidelines.","科學家必須遵守道德準則。"],
  ["evaluate","v.","評估/評價",6,"Please evaluate the risks carefully.","請仔細評估風險。"],
  ["evolve","v.","演化/發展",6,"Languages evolve over time.","語言隨著時間不斷演化。"],
  ["exclude","v.","排除/排斥",6,"Don't exclude anyone from the group.","不要排斥任何一個人。"],
  ["explicit","adj.","明確的/清晰的",6,"Give explicit instructions.","給出明確的指示。"],
  ["exploit","v./n.","開發/剝削",6,"We should not exploit natural resources.","我們不應過度開發自然資源。"],
  ["expose","v.","暴露/揭露",6,"The report exposed the corruption.","這份報告揭露了腐敗行為。"],
  ["facilitate","v.","促進/使容易",6,"Technology facilitates communication.","科技促進了溝通。"],
  ["fluctuate","v.","波動",6,"Prices fluctuate with supply and demand.","價格隨供求關係波動。"],
  ["formulate","v.","制定/構想",6,"They formulated a new policy.","他們制定了一項新政策。"],
  ["fundamental","adj.","基本的/根本的",6,"Trust is fundamental to any relationship.","信任是任何關係的基礎。"],
  ["hazardous","adj.","危險的/有害的",6,"Hazardous chemicals must be stored safely.","危險化學品必須安全存放。"],
  ["hierarchy","n.","等級制度",6,"Every organization has a hierarchy.","每個組織都有等級制度。"],
  ["hinder","v.","阻礙",6,"Lack of sleep hinders learning.","睡眠不足會阻礙學習。"],
  ["ideology","n.","意識形態",6,"Political ideology shapes policies.","政治意識形態影響政策。"],
  ["implement","v.","實施/執行",6,"It's time to implement the plan.","是時候執行計劃了。"],
  ["implicit","adj.","隱含的/含蓄的",6,"There is an implicit trust between them.","他們之間有一種默契的信任。"],
  ["infrastructure","n.","基礎設施",6,"Good infrastructure supports economic growth.","良好的基礎設施支撐經濟成長。"],
  ["inherent","adj.","固有的/天生的",6,"There is an inherent risk in every business.","每項業務都有固有的風險。"],
  ["initiative","n.","主動性/倡議",6,"Take initiative and lead the project.","主動出擊，帶領這個專案。"],
  ["innovate","v.","創新",6,"Companies must innovate to survive.","公司必須創新才能生存。"],
  ["integrity","n.","正直/誠信",6,"A leader must have integrity.","領導者必須具備誠信。"],
  ["intense","adj.","強烈的/激烈的",6,"The competition was intense.","競爭非常激烈。"],
  ["interact","v.","互動",6,"Children learn by interacting with others.","孩子們通過與他人互動來學習。"],
  ["leverage","n./v.","槓桿/利用",6,"Use technology as leverage.","利用技術作為優勢。"],
  ["manipulate","v.","操縱",6,"Don't let others manipulate you.","不要讓別人操縱你。"],
  ["mechanism","n.","機制/機械裝置",6,"What is the mechanism behind this?","這背後的機制是什麼？"],
  ["minimize","v.","最小化/降到最低",6,"Minimize the risk by planning ahead.","提前規劃以降低風險。"],
  ["notorious","adj.","惡名昭彰的",6,"He is notorious for his temper.","他以暴脾氣聞名。"],
  ["paradox","n.","矛盾/悖論",6,"It's a paradox that the rich can be lonely.","富人也可能孤獨，這是個矛盾。"],
  ["phenomenon","n.","現象",6,"Social media is a modern phenomenon.","社群媒體是現代現象。"],
  ["portfolio","n.","作品集/投資組合",6,"She showed her design portfolio.","她展示了她的設計作品集。"],
  ["preliminary","adj.","初步的/預備的",6,"Preliminary results look promising.","初步結果看起來很有希望。"],
  ["prevalent","adj.","普遍的/流行的",6,"Smartphones are prevalent worldwide.","智慧型手機在全球普及。"],
  ["proceed","v.","繼續/進行",6,"Please proceed with the presentation.","請繼續進行報告。"],
  ["profound","adj.","深刻的/深遠的",6,"The experience had a profound impact.","這段經歷產生了深遠的影響。"],
  ["prohibit","v.","禁止",6,"Smoking is prohibited in this area.","這個區域禁止吸菸。"],
  ["rationale","n.","根本原因/理由",6,"Explain the rationale behind your decision.","解釋你決策背後的理由。"],
  ["reinforce","v.","強化/加固",6,"Practice reinforces learning.","練習強化了學習效果。"],
  ["renewable","adj.","可再生的",6,"Solar power is a renewable energy source.","太陽能是一種可再生能源。"],
  ["resilient","adj.","有韌性的/彈性的",6,"She is resilient in the face of hardship.","她面對困難時很有韌性。"],
  ["revenue","n.","收入/收益",6,"The company's revenue increased by 20%.","公司收入增加了20%。"],
  ["scrutinize","v.","仔細審查",6,"The committee scrutinized the budget.","委員會仔細審查了預算。"],
  ["simultaneously","adv.","同時地",6,"She can work on two projects simultaneously.","她可以同時進行兩個項目。"],
  ["skeptical","adj.","懷疑的",6,"I am skeptical about that claim.","我對那個說法持懷疑態度。"],
  ["sophisticated","adj.","複雜的/精密的",6,"The technology is highly sophisticated.","這項技術高度複雜。"],
  ["stereotype","n./v.","刻板印象",6,"Avoid stereotyping people by their appearance.","避免以外貌對人進行刻板印象。"],
  ["stimulate","v.","刺激/激勵",6,"Reading stimulates the imagination.","閱讀刺激想像力。"],
  ["substantial","adj.","大量的/實質的",6,"She made a substantial contribution.","她做出了實質性的貢獻。"],
  ["suppress","v.","壓制/抑制",6,"Don't suppress your emotions.","不要壓抑你的情感。"],
  ["sustainable","adj.","可持續的",6,"Sustainable development protects the future.","可持續發展保護了未來。"],
  ["synthesize","v.","綜合/合成",6,"She synthesized information from many sources.","她綜合了許多來源的信息。"],
  ["transparent","adj.","透明的",6,"The government should be transparent.","政府應該保持透明。"],
  ["ultimate","adj.","最終的/極致的",6,"What is your ultimate goal?","你最終的目標是什麼？"],
  ["undermine","v.","削弱/破壞",6,"Don't undermine others' confidence.","不要削弱別人的信心。"],
  ["unprecedented","adj.","前所未有的",6,"The storm caused unprecedented damage.","這場風暴造成了前所未有的破壞。"],
  ["versatile","adj.","多才多藝的/多用途的",6,"She is a versatile musician.","她是一位多才多藝的音樂家。"],
  ["viable","adj.","可行的",6,"Is this plan economically viable?","這個計劃在經濟上可行嗎？"],
];
