// 大考中心高中英文參考詞彙表（節錄）
// 格式：[單字, 詞性, 中文意思, 等級, 英文例句, 中文例句翻譯]
const VOCAB = [
  ["abandon","v.","放棄",4,"She had to abandon her car in the snow.","她不得不將車子遺棄在雪地裡。"],
  ["ability","n.","能力",2,"He has the ability to learn quickly.","他有快速學習的能力。"],
  ["able","adj.","能夠的",1,"Are you able to help me?","你能幫我嗎？"],
  ["absolute","adj.","絕對的",4,"The law requires absolute honesty.","法律要求絕對誠實。"],
  ["absorb","v.","吸收",4,"Plants absorb sunlight to make energy.","植物吸收陽光來製造能量。"],
  ["abstract","adj.","抽象的",4,"Love is an abstract concept.","愛是個抽象概念。"],
  ["absurd","adj.","荒謬的",5,"It's absurd to stay up all night.","徹夜不眠是荒謬的。"],
  ["abundant","adj.","豐富的",5,"Fresh water is abundant in Taiwan.","台灣淡水資源豐富。"],
  ["academic","adj.","學術的",4,"She has a strong academic record.","她有優秀的學術成績。"],
  ["accelerate","v.","加速",6,"The car accelerated past the limit.","這輛車超速加速行駛。"],
  ["accept","v.","接受",2,"Please accept my apology.","請接受我的道歉。"],
  ["accident","n.","意外",3,"There was a car accident on the road.","路上發生了一起車禍。"],
  ["accompany","v.","陪伴",4,"She accompanied him to the hospital.","她陪他去醫院。"],
  ["accomplish","v.","完成",4,"We accomplished our goal ahead of time.","我們提前完成了目標。"],
  ["accurate","adj.","準確的",3,"The weather forecast was accurate.","天氣預報很準確。"],
  ["accuse","v.","指控",4,"He was accused of stealing.","他被指控偷竊。"],
  ["achieve","v.","達成",3,"Hard work helps you achieve your dreams.","努力幫助你實現夢想。"],
  ["acknowledge","v.","承認",5,"She acknowledged her mistake.","她承認了自己的錯誤。"],
  ["acquire","v.","獲得",4,"He acquired a new skill online.","他在網路上習得了一項新技能。"],
  ["act","n./v.","行動",1,"We must act quickly.","我們必須迅速行動。"],
  ["active","adj.","積極的",2,"Stay active to keep healthy.","保持積極以維持健康。"],
  ["activity","n.","活動",3,"Outdoor activities are good for kids.","戶外活動對孩子們有益。"],
  ["adapt","v.","適應",4,"It takes time to adapt to a new city.","適應一座新城市需要時間。"],
  ["add","v.","增加",1,"Add some salt to the soup.","在湯裡加一些鹽。"],
  ["adequate","adj.","足夠的",4,"Make sure you get adequate sleep.","確保你有足夠的睡眠。"],
  ["adjust","v.","調整",4,"Please adjust the volume.","請調整音量。"],
  ["admire","v.","欽佩",3,"I admire her courage.","我欽佩她的勇氣。"],
  ["admit","v.","承認",3,"He finally admitted the truth.","他終於承認了事實。"],
  ["adopt","v.","採用/收養",3,"They decided to adopt a puppy.","他們決定收養一隻小狗。"],
  ["adult","n./adj.","成人",1,"This movie is for adults only.","這部電影僅限成人觀看。"],
  ["advance","n./v.","進步",2,"Technology advances every year.","科技每年都在進步。"],
  ["advantage","n.","優勢",3,"Hard work gives you an advantage.","勤奮努力讓你更有優勢。"],
  ["adventure","n.","冒險",3,"Life is a great adventure.","人生是一場偉大的冒險。"],
  ["advice","n.","建議",3,"Let me give you some advice.","讓我給你一些建議。"],
  ["affect","v.","影響",3,"Weather affects our mood.","天氣影響我們的情緒。"],
  ["afford","v.","負擔得起",3,"I can't afford a new phone.","我買不起新手機。"],
  ["afraid","adj.","害怕的",1,"Don't be afraid of making mistakes.","不要害怕犯錯。"],
  ["agree","v.","同意",1,"I agree with your point.","我同意你的觀點。"],
  ["agriculture","n.","農業",3,"Agriculture feeds the world.","農業養活了整個世界。"],
  ["aid","n./v.","幫助",2,"First aid can save lives.","急救能救人性命。"],
  ["aim","n./v.","目標/瞄準",2,"My aim is to pass the exam.","我的目標是通過考試。"],
  ["alarm","n./v.","警報",2,"The fire alarm went off suddenly.","火警突然響起。"],
  ["allow","v.","允許",1,"Dogs are not allowed inside.","裡面不允許帶狗進入。"],
  ["alternative","adj./n.","替代的",6,"We need an alternative solution.","我們需要一個替代方案。"],
  ["amaze","v.","使驚奇",3,"Her performance amazed everyone.","她的表演讓所有人驚嘆。"],
  ["ambition","n.","野心",3,"He has the ambition to become a doctor.","他有成為醫生的抱負。"],
  ["analyze","v.","分析",4,"We need to analyze the data carefully.","我們需要仔細分析這些資料。"],
  ["anger","n.","憤怒",1,"Take a deep breath to control your anger.","深呼吸來控制你的憤怒。"],
  ["announce","v.","宣布",3,"The teacher announced the test date.","老師宣布了考試日期。"],
  ["appear","v.","出現",1,"Stars appear at night.","星星在夜晚出現。"],
  ["appreciate","v.","感激/欣賞",3,"I appreciate your help very much.","我非常感激你的幫助。"],
  ["arrange","v.","安排",2,"Can you arrange a meeting?","你能安排一次會議嗎？"],
  ["arrive","v.","到達",2,"The train arrives at 8 p.m.","火車晚上八點到達。"],
  ["ask","v.","詢問",1,"Please ask if you have questions.","如果有問題請提問。"],
  ["assist","v.","協助",3,"The nurse assisted the doctor.","護士協助了醫生。"],
  ["assume","v.","假設",4,"Don't assume you already know everything.","不要假設你已經什麼都知道。"],
  ["assure","v.","保證",4,"I assure you it's safe.","我向你保證這是安全的。"],
  ["athlete","n.","運動員",3,"She trained hard to become an athlete.","她努力訓練以成為運動員。"],
  ["atmosphere","n.","大氣/氣氛",4,"The atmosphere in the hall was exciting.","大廳裡的氣氛令人興奮。"],
  ["attack","v./n.","攻擊",2,"The dog attacked the stranger.","那隻狗攻擊了陌生人。"],
  ["attempt","v./n.","嘗試",3,"This is my first attempt at cooking.","這是我第一次嘗試做飯。"],
  ["attend","v.","出席",2,"All students must attend class.","所有學生都必須上課。"],
  ["avoid","v.","避免",3,"Try to avoid eating junk food.","盡量避免吃垃圾食物。"],
  ["aware","adj.","意識到的",3,"Be aware of your surroundings.","要注意你周圍的環境。"],
  ["balance","n./v.","平衡",3,"Work-life balance is important.","工作與生活的平衡很重要。"],
  ["barrier","n.","障礙",4,"Language can be a barrier to learning.","語言可能是學習的障礙。"],
  ["behave","v.","表現",3,"Please behave yourself in class.","請在課堂上注意行為。"],
  ["believe","v.","相信",1,"I believe you can do it.","我相信你能做到。"],
  ["benefit","n./v.","好處",3,"Exercise has many health benefits.","運動對健康有許多好處。"],
  ["brave","adj.","勇敢的",2,"She was brave enough to speak up.","她勇敢地站出來說話。"],
  ["breathe","v.","呼吸",2,"Take a moment to breathe deeply.","花點時間深呼吸。"],
  ["burden","n./v.","負擔",4,"Don't let stress become a burden.","不要讓壓力變成負擔。"],
  ["calm","adj./v.","冷靜的",2,"Stay calm during the test.","考試時保持冷靜。"],
  ["capable","adj.","有能力的",3,"She is capable of great things.","她有能力做成大事。"],
  ["care","n./v.","關心",1,"Care for others as you care for yourself.","關心他人就像關心自己一樣。"],
  ["career","n.","職業生涯",3,"Choose a career you are passionate about.","選擇你熱愛的職業。"],
  ["cause","n./v.","原因/導致",2,"Pollution causes serious harm to health.","污染對健康造成嚴重傷害。"],
  ["celebrate","v.","慶祝",3,"We celebrate the New Year with fireworks.","我們用煙火慶祝新年。"],
  ["challenge","n./v.","挑戰",3,"Every challenge is a chance to grow.","每一個挑戰都是成長的機會。"],
  ["change","n./v.","改變",1,"Change is part of life.","改變是生活的一部分。"],
  ["choose","v.","選擇",1,"Choose the right path for yourself.","為自己選擇正確的道路。"],
  ["communicate","v.","溝通",3,"It's important to communicate clearly.","清楚地溝通是很重要的。"],
  ["compete","v.","競爭",3,"Students compete for top grades.","學生們競相爭取高分。"],
  ["complex","adj.","複雜的",4,"This problem is very complex.","這個問題非常複雜。"],
  ["concern","n./v.","擔心/關切",3,"I'm concerned about your health.","我擔心你的健康。"],
  ["confident","adj.","有信心的",3,"Be confident when you speak in public.","公開演講時要有自信。"],
  ["conflict","n./v.","衝突",4,"Avoid conflict by listening carefully.","仔細聆聽以避免衝突。"],
  ["consequence","n.","後果",4,"Think before you act to avoid bad consequences.","行動前三思以避免不良後果。"],
  ["control","n./v.","控制",2,"Keep your emotions under control.","保持情緒受控。"],
  ["courage","n.","勇氣",3,"It takes courage to admit a mistake.","承認錯誤需要勇氣。"],
  ["create","v.","創造",2,"Artists create beauty with their work.","藝術家用作品創造美。"],
  ["curious","adj.","好奇的",3,"Children are naturally curious.","孩子天生就充滿好奇心。"],
  ["danger","n.","危險",2,"The hiker was in danger of falling.","登山者有跌倒的危險。"],
  ["decide","v.","決定",2,"It's hard to decide between two choices.","在兩個選擇之間做決定很難。"],
  ["demand","n./v.","需求/要求",3,"There is high demand for good teachers.","對優秀教師的需求很高。"],
  ["depend","v.","依賴",2,"Young children depend on their parents.","小孩子依賴他們的父母。"],
  ["describe","v.","描述",2,"Can you describe what happened?","你能描述一下發生了什麼嗎？"],
  ["develop","v.","發展",2,"We develop new habits over time.","我們隨著時間發展出新習慣。"],
  ["discover","v.","發現",2,"Scientists discover new things every day.","科學家每天都在發現新事物。"],
  ["dream","n./v.","夢想",1,"Never stop chasing your dream.","永遠不要停止追逐你的夢想。"],
  ["duty","n.","責任",3,"It's our duty to protect the environment.","保護環境是我們的責任。"],
  ["earn","v.","賺得",2,"You earn respect through your actions.","你透過行動贏得尊重。"],
  ["educate","v.","教育",3,"Education can change a person's life.","教育可以改變一個人的人生。"],
  ["effort","n.","努力",2,"Success requires consistent effort.","成功需要持續的努力。"],
  ["emotion","n.","情感",3,"Music can trigger strong emotions.","音樂能觸發強烈的情感。"],
  ["encourage","v.","鼓勵",3,"Parents should encourage their children.","父母應該鼓勵孩子。"],
  ["enjoy","v.","享受",1,"I enjoy reading before bed.","我喜歡睡前閱讀。"],
  ["environment","n.","環境",3,"We must protect our environment.","我們必須保護我們的環境。"],
  ["escape","v./n.","逃跑",3,"The bird escaped from its cage.","那隻鳥從籠子裡逃了出去。"],
  ["experience","n./v.","經驗",2,"Travel gives you valuable experience.","旅行給你寶貴的經驗。"],
  ["explain","v.","解釋",2,"Can you explain this to me again?","你能再解釋一遍嗎？"],
  ["fail","v.","失敗",2,"Don't be afraid to fail and try again.","不要怕失敗，再接再厲。"],
  ["famous","adj.","著名的",2,"Taiwan is famous for its night markets.","台灣以夜市聞名。"],
  ["focus","n./v.","專注",3,"Focus on one thing at a time.","一次專注於一件事。"],
  ["freedom","n.","自由",3,"Everyone deserves freedom of speech.","每個人都應享有言論自由。"],
  ["goal","n.","目標",2,"Set a clear goal for yourself.","為自己設定一個清晰的目標。"],
  ["grateful","adj.","感激的",4,"I'm grateful for all your support.","我對你所有的支持感到感激。"],
  ["grow","v.","成長",1,"Children grow so fast.","孩子們長得好快。"],
  ["habit","n.","習慣",3,"Reading is a good habit to develop.","閱讀是一個值得培養的好習慣。"],
  ["harm","n./v.","傷害",3,"Smoking can harm your lungs.","吸菸會傷害你的肺。"],
  ["honest","adj.","誠實的",2,"Be honest even when it's difficult.","即使困難，也要誠實。"],
  ["hope","n./v.","希望",1,"Never lose hope.","永遠不要失去希望。"],
  ["imagine","v.","想像",2,"Imagine a world without pollution.","想像一個沒有污染的世界。"],
  ["improve","v.","改善",2,"Practice daily to improve your skills.","每天練習以提升你的技能。"],
  ["inspire","v.","激勵",4,"Great leaders inspire others to act.","偉大的領導者激勵他人採取行動。"],
  ["interest","n./v.","興趣",1,"Develop an interest in reading.","培養對閱讀的興趣。"],
  ["judge","v./n.","判斷/法官",3,"Don't judge others too quickly.","不要太快評判別人。"],
  ["knowledge","n.","知識",2,"Knowledge is power.","知識就是力量。"],
  ["learn","v.","學習",1,"We learn from our mistakes.","我們從錯誤中學習。"],
  ["limit","n./v.","限制",3,"There is a time limit for the test.","考試有時間限制。"],
  ["manage","v.","管理",3,"She manages her time very well.","她把時間管理得非常好。"],
  ["memory","n.","記憶",2,"I have a great memory for faces.","我對面孔有很強的記憶力。"],
  ["moral","adj./n.","道德的",4,"We must make moral decisions.","我們必須做出道德的決定。"],
  ["motivate","v.","激勵",4,"What motivates you to study?","是什麼激勵你學習？"],
  ["necessary","adj.","必要的",2,"Sleep is necessary for good health.","睡眠對健康來說是必要的。"],
  ["negative","adj.","負面的",3,"Avoid negative thinking.","避免負面思考。"],
  ["nervous","adj.","緊張的",2,"I felt nervous before the speech.","演講前我感到緊張。"],
  ["opportunity","n.","機會",3,"Don't miss this great opportunity.","不要錯過這個好機會。"],
  ["organize","v.","組織",3,"Organize your notes after class.","課後整理你的筆記。"],
  ["patient","adj./n.","耐心的/病人",2,"Be patient; good things take time.","要有耐心，好事需要時間。"],
  ["perform","v.","執行/表演",3,"She performed beautifully on stage.","她在台上表演得非常漂亮。"],
  ["plan","n./v.","計劃",1,"Plan your day the night before.","前一晚計畫好隔天的行程。"],
  ["positive","adj.","正面的",3,"Keep a positive attitude every day.","每天保持積極的態度。"],
  ["prepare","v.","準備",2,"Prepare well before the exam.","考試前充分準備。"],
  ["prevent","v.","預防",3,"Wash your hands to prevent illness.","洗手以預防疾病。"],
  ["problem","n.","問題",1,"Every problem has a solution.","每個問題都有解決方法。"],
  ["promise","n./v.","承諾",2,"Always keep your promises.","永遠遵守你的承諾。"],
  ["protect","v.","保護",2,"We must protect our oceans.","我們必須保護我們的海洋。"],
  ["provide","v.","提供",2,"Libraries provide free access to books.","圖書館免費提供書籍。"],
  ["purpose","n.","目的",3,"What is the purpose of this project?","這個計劃的目的是什麼？"],
  ["realize","v.","意識到",2,"I realized I had made a mistake.","我意識到我犯了一個錯誤。"],
  ["reason","n.","理由",2,"Give me a good reason to trust you.","給我一個信任你的好理由。"],
  ["recognize","v.","認識",3,"I didn't recognize her at first.","我起初沒認出她。"],
  ["reduce","v.","減少",3,"We should reduce waste every day.","我們每天都應該減少浪費。"],
  ["respect","n./v.","尊重",2,"Respect is earned, not given.","尊重是贏得的，不是給予的。"],
  ["responsibility","n.","責任",3,"Taking responsibility shows maturity.","承擔責任體現成熟。"],
  ["risk","n./v.","風險",3,"Every decision carries some risk.","每個決定都帶有一些風險。"],
  ["save","v.","拯救/儲存",1,"Save your work before you close.","關閉前記得儲存你的工作。"],
  ["serious","adj.","嚴肅的",2,"This is a serious situation.","這是一個嚴峻的情況。"],
  ["share","v./n.","分享",2,"Share what you know with others.","把你知道的東西與他人分享。"],
  ["skill","n.","技能",2,"Communication is a vital skill.","溝通是一項重要技能。"],
  ["solve","v.","解決",2,"We need to solve this together.","我們需要一起解決這個問題。"],
  ["support","n./v.","支持",2,"Thank you for your support.","感謝你的支持。"],
  ["talent","n.","才能",3,"She has a talent for music.","她有音樂才能。"],
  ["technology","n.","科技",3,"Technology changes how we live.","科技改變了我們的生活方式。"],
  ["think","v.","思考",1,"Think before you speak.","說話前先思考。"],
  ["tradition","n.","傳統",3,"Every culture has its own traditions.","每種文化都有自己的傳統。"],
  ["trust","n./v.","信任",2,"Trust is the foundation of friendship.","信任是友誼的基礎。"],
  ["understand","v.","理解",1,"Do you understand the question?","你理解這個問題嗎？"],
  ["unique","adj.","獨特的",3,"Everyone is unique in their own way.","每個人都有自己獨特的地方。"],
  ["value","n./v.","價值",2,"Family values are very important.","家庭價值觀非常重要。"],
  ["wisdom","n.","智慧",4,"Wisdom comes with experience.","智慧隨著經驗而來。"],
  ["wonderful","adj.","精彩的",1,"What a wonderful day it is!","多美好的一天啊！"],
  ["work","n./v.","工作",1,"Hard work always pays off.","努力工作總是會有回報的。"],
];
